#!/bin/bash

# Quick Reference Script
# Shows all available test scenarios and options

echo "=========================================="
echo "🏦 Banking System Stress Test - Quick Reference"
echo "=========================================="
echo ""
echo "📋 Available Test Scenarios:"
echo ""
echo "1. SMOKE TEST (Quick Verification)"
echo "   Script: ./run-smoke-test.sh"
echo "   Purpose: Verify system is working"
echo "   Duration: ~30 seconds"
echo ""
echo "2. BALANCED LOAD TEST"
echo "   Script: ./run-balanced-test.sh"
echo "   Scenario: BALANCED_LOAD (40% deposits, 30% withdrawals, 30% transfers)"
echo "   Purpose: General system performance evaluation"
echo ""
echo "3. READ-HEAVY TEST"
echo "   Script: ./run-read-heavy-test.sh"
echo "   Scenario: READ_HEAVY (80% deposits, 10% withdrawals, 10% transfers)"
echo "   Purpose: Test read-heavy workloads"
echo ""
echo "4. WITHDRAWAL-HEAVY TEST"
echo "   Script: ./run-withdrawal-heavy-test.sh"
echo "   Scenario: WITHDRAWAL_HEAVY (10% deposits, 80% withdrawals, 10% transfers)"
echo "   Purpose: Test withdrawal performance and validation"
echo ""
echo "5. HEAVY TRANSFERS TEST"
echo "   Script: ./run-heavy-transfers-test.sh"
echo "   Scenario: HEAVY_TRANSFERS (20% deposits, 20% withdrawals, 60% transfers)"
echo "   Purpose: Test transfer performance with mixed operations"
echo ""
echo "6. TRANSFER STRESS TEST"
echo "   Script: ./run-transfer-stress-test.sh"
echo "   Scenario: STRESS_TRANSFERS (100% transfers)"
echo "   Purpose: Maximum concurrency stress test"
echo ""
echo "7. ANALYSIS TEST"
echo "   Script: ./run-analysis-test.sh"
echo "   Purpose: Generate comprehensive analysis data"
echo ""
echo "8. COMPLETE TEST SUITE"
echo "   Script: ./run-all-scenarios.sh"
echo "   Purpose: Run all scenarios sequentially"
echo ""
echo "=========================================="
echo "⚙️  Command Line Options:"
echo "=========================================="
echo ""
echo "java NetworkStressTest [options]"
echo ""
echo "--scenario <SCENARIO>    Test scenario"
echo "  BALANCED_LOAD         40% deposits, 30% withdrawals, 30% transfers"
echo "  HEAVY_TRANSFERS       20% deposits, 20% withdrawals, 60% transfers"
echo "  READ_HEAVY            80% deposits, 10% withdrawals, 10% transfers"
echo "  STRESS_TRANSFERS      100% transfers"
echo "  WITHDRAWAL_HEAVY      10% deposits, 80% withdrawals, 10% transfers"
echo ""
echo "--output <FORMAT>       Output format"
echo "  CONSOLE               Console output only"
echo "  CSV                   CSV file for spreadsheet analysis"
echo "  JSON                  JSON file for programmatic analysis"
echo "  BOTH                  Both CSV and JSON files"
echo ""
echo "--progress              Enable real-time progress reporting (default)"
echo "--no-progress           Disable progress reporting"
echo "--help                  Show help message"
echo ""
echo "=========================================="
echo "📊 Output Files:"
echo "=========================================="
echo ""
echo "stress-test-results.csv     Spreadsheet-compatible data"
echo "stress-test-results.json    Structured analysis data"
echo "logs/application.log        Detailed execution logs"
echo ""
echo "=========================================="
echo "🚀 Quick Start Examples:"
echo "=========================================="
echo ""
echo "# Run a quick smoke test"
echo "./run-smoke-test.sh"
echo ""
echo "# Run balanced load test with analysis output"
echo "./run-analysis-test.sh"
echo ""
echo "# Run custom scenario"
echo "java -cp \"../target/classes:stress-test/target/classes:../target/dependency/*\" \\"
echo "  com.bank.stress.NetworkStressTest \\"
echo "  --scenario HEAVY_TRANSFERS \\"
echo "  --output BOTH \\"
echo "  --progress"
echo ""
echo "# Run complete test suite"
echo "./run-all-scenarios.sh"
echo ""
echo "=========================================="
echo "📈 Analysis Tips:"
echo "=========================================="
echo ""
echo "1. Import CSV files into Excel/LibreOffice for charts"
echo "2. Use JSON files for custom analysis scripts"
echo "3. Review logs for performance bottlenecks"
echo "4. Compare results across different scenarios"
echo "5. Focus on P95/P99 response times for outliers"
echo ""
echo "Happy Stress Testing! 🚀"